// Authentication is fully handled by Better Auth.
// See: src/routes/auth.ts — mounts auth.handler() for all /auth/* routes
//
// Available endpoints (auto-generated by Better Auth):
//   POST /api/auth/sign-up/email     — register with username + password
//   POST /api/auth/sign-in/username  — login with username
//   POST /api/auth/sign-in/anonymous — create anonymous session
//   GET  /api/auth/sign-in/social/google — Google OAuth
//   POST /api/auth/sign-out          — logout
//   GET  /api/auth/get-session       — current session
